### ISSUE TITLE
cant create binary

### ISSUE THREAD

**Issue by pikaboo** [Adorkable/seguecode#19]
How do you create the seguecode binary ?

I tried installing the plugin from alcatraz, and from source code, building the project  seguecodePlugin scheme does not create the binary, and building seguecode scheme gives too many errors on my computer. Can you simply upload a binary i can use ?

**Comment by yoiang** [comment]
Hey @pikaboo !
I'm going to update the plugin today to support Xcode 7, that may resolve your issue!

I will upload a binary as well, the only gotcha is that being a swift project with custom frameworks to properly run the binary you do need those frameworks available. You can already download a bundle that includes the latest binary and the frameworks (2.1.1) here: [seguecode.bundle.zip](https://github.com/Adorkable/seguecode/releases/download/2.1.1/seguecode.bundle.zip). It's silly but to run it from command line you'll still running the binary directly from within the bundle, ie *[PATH]/seguecode.bundle/Contents/MacOS/seguecode*

I'll elaborate on the documentation, the **seguecodePlugin** scheme actually downloads the **seguecode.bundle.zip** associated with the plugin version, to build the executable you should build the **seguecode** scheme, the **seguecodeBundle** scheme, or the **seguecodePlugin** Local scheme.

**Comment by yoiang** [comment]
@pikaboo version 2.2.0 is out, give it a go with Xcode 7 and Alcatraz, let me know if it doesn't work.

Again you can also download the latest bundle (2.2.0) with the binary here: [seguecode.bundle.zip](https://github.com/Adorkable/seguecode/releases/download/2.2.0/seguecode.bundle.zip)

**Comment by pikaboo** [comment]
Hi, I downloaded the binary,

and put it somewhere near my project, then got this when building the project

![image](https://cloud.githubusercontent.com/assets/3405551/9987255/c68496c4-604e-11e5-982a-cc0990423ef1.png)


What am I missinging/ doing incorrectly ?

**Comment by pikaboo** [comment]
here is what i get when i run it from the command line

```Lenas-MBP:devtools Lena$ ./seguecode -v
   dyld: Library not loaded: @rpath/seguecodeKit.framework/Versions/A/seguecodeKit
   Referenced from: /Users/Lena/Dev/workspace/mp4-ios/devtools/./seguecode
   Reason: image not found
   Trace/BPT trap: 5```

**Comment by yoiang** [comment]
Hey @pikaboo ! 
So the error is saying that it's looking for the framework **seguecodeKit**, one of the required frameworks.

As mentioned above because Swift does not allow us to compile all libraries into one executable we cannot run the **seguecode** executable alone, it must be run from a location where it can find the required frameworks. 

The easiest way to accomplish this is by running it from within **seguecode.bundle**:
`./seguecode.bundle/Contents/MacOS/seguecode`

**Comment by yoiang** [comment]
@pikaboo have you had a chance to try this?
