### ISSUE TITLE
Not working for Xcode 7.1

### ISSUE THREAD

**Issue by hardikdevios** [Adorkable/seguecode#21]
Xcode 7.1 is now officially released please update the plugin

**Comment by yoiang** [comment]
Should work now! I haven't been able to get Alcatraz working with 7.1 so I can't test the Alcatraz install but works when manually installed!

Lemme know if it works or there's still an issue. Thanks for reporting!

**Comment by yoiang** [comment]
@hardikdevios have you had a chance to test this?

**Comment by hardikdevios** [comment]
cheers buddy :+1:
