### ISSUE TITLE
I finally got it to work and was so disappointed with the result

### ISSUE THREAD

**Issue by pikaboo** [Adorkable/seguecode#26]
Hi,

After lots of messing around I finally got seguecode to work with a runscript build phase
however, I was very disappointed with the result.

My entire project is written in objectiveC and I do not want to start switching to swift right now
The result came in swift, when i expected it to be in objectiveC
can you add a flag or something to get the result in objectiveC ?

your entire help file shows that the generated code is in objective c

and i did not want nor expect it to be in swift :(

**Comment by yoiang** [comment]
Hey @pikaboo ! 
Thanks for letting me know your concern. Until Objective-C output is readded you can use this release or build from this commit: [1.1.1](https://github.com/Adorkable/seguecode/releases/tag/1.1.1). I'll let you know when Objective-C output it added again!
